services:
  - type: web
    name: assistente-financeiro
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.mtbnwljjznjvmlnmtzbl:Mt%2422012004%40Rv@aws-0-us-east-2.pooler.supabase.com:5432/postgres
      - key: RESEND_API_KEY
        sync: false
